# Packs embedded-web/index.html into solar_monitor_v3/web_index.h (gzip, as a C byte array).
# Run after editing the dashboard:  powershell -ExecutionPolicy Bypass -File build_web.ps1
$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$src = Join-Path $root "embedded-web\index.html"
$dst = Join-Path $root "solar_monitor_v3\web_index.h"

$bytes = [IO.File]::ReadAllBytes($src)
$ms = New-Object IO.MemoryStream
$gz = New-Object IO.Compression.GZipStream($ms, [IO.Compression.CompressionLevel]::Optimal)
$gz.Write($bytes, 0, $bytes.Length)
$gz.Close()
$z = $ms.ToArray()

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine("// Generated by build_web.ps1 from embedded-web/index.html - do not edit by hand.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <Arduino.h>")
[void]$sb.AppendLine("const size_t INDEX_HTML_GZ_LEN = $($z.Length);")
[void]$sb.Append("const uint8_t INDEX_HTML_GZ[] PROGMEM = {")
for ($i = 0; $i -lt $z.Length; $i++) {
  if ($i % 24 -eq 0) { [void]$sb.Append("`n  ") }
  [void]$sb.Append($z[$i]).Append(",")
}
[void]$sb.AppendLine("`n};")
[IO.File]::WriteAllText($dst, $sb.ToString())
Write-Host ("embedded-web/index.html {0:N0} bytes -> gzip {1:N0} bytes -> {2}" -f $bytes.Length, $z.Length, $dst)
